[book]
title = "Ngân Giang Resume"
authors = ["Ngân Giang"]
description = "Ngân Giang Resume"
language = "vn"
multilingual = true
src = "src"

[rust]
edition = "2021"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
mathjax-support = false
copy-fonts = true
no-section-label = false
git-repository-url = "https://www.linkedin.com/in/nguyenngangiang/"
git-repository-icon = "fa-linkedin"
input-404 = "404.md"